name: Build Home Assistant Wrapper

on:
  schedule:
    - cron: "0 2 * * *" # check daily at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if base image was updated
        id: check
        uses: lucacome/docker-image-update-checker@v3.0.1
        with:
          base-image: ghcr.io/home-assistant/home-assistant:stable
          image: ghcr.io/${{ github.repository_owner }}/hass-plus:latest
          platforms: linux/amd64,linux/arm64

  build:
    needs: check-upstream
    if: needs.check-upstream.outputs.needs-updating == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Log in to GHCR
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.7.0
        with:
          platforms: arm64

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hass-plus:latest
          platforms: linux/amd64,linux/arm64
